### PR TITLE
Handle Administrate::Field::Date in the Exporter Service

### PR DESCRIPTION
**Pull request by moveson**
Addresses #31

### CODE REVIEW

**Comment by ACPK** [comment]
@SourceLabsLLC  - Thoughts on merging this?

**Comment by andreibondarev** [comment]
@moveson Very nice! I'll give it a quick test this evening, merge, and cut a new release tag! Thank you!!

**Comment by andreibondarev** [comment]
@moveson Btw-- you can always transform the output as you please via the `transform_on_export:` option:

```
created_at: Field::DateTime.with_options(transform_on_export: -> (field) { field.data.strftime("%F") })
```

**Comment by moveson** [comment]
> @moveson Btw-- you can always transform the output as you please via the `transform_on_export:` option:
> 
> ```
> created_at: Field::DateTime.with_options(transform_on_export: -> (field) { field.data.strftime("%F") })
> ```

Yeah, that's exactly what we did. But it took me some time to realize the problem and then figure out how to do that. Thanks for merging this--hopefully will help others in the future.

**Pull request merged**
